/* Query 1 */
Spool result1.lst
SELECT L.LID, L.LEAGUE_NAME, R.REGION_NAME, L.YEAR
FROM LEAGUES L, REGIONS R
WHERE R.RID = L.RID AND (L.SEASON='Spring' OR L.SEASON='Summer')
ORDER BY L.LID ASC;
Spool Off

/* Query 2 */
Spool result2.lst
SELECT DISTINCT T.TID, T.TEAM_NAME, T.AVERAGE_AGE
FROM LEAGUES L, TEAMS T
WHERE L.CHAMPION_TID = T.TID AND L.SEASON = 'Autumn' AND L.YEAR>=2015
GROUP BY T.TID, T.TEAM_NAME, T.AVERAGE_AGE
HAVING COUNT(DISTINCT(L.LID)) > 1
ORDER BY T.TID ASC;
Spool Off

/* Query 3 */
CREATE OR REPLACE VIEW TEMP3 AS
SELECT TID, TEAM_NAME, AVERAGE_AGE, SEASON, COUNT(*) AS W_NUM
FROM TEAMS T, LEAGUES L
WHERE TID = CHAMPION_TID
GROUP BY TID, TEAM_NAME, AVERAGE_AGE, SEASON;
Spool result3.lst
SELECT * FROM TEMP3 T1
WHERE W_NUM = (SELECT MAX(T2.W_NUM) FROM TEMP3 T2 WHERE T1.SEASON = T2.SEASON)
ORDER BY TID ASC,SEASON ASC;
Spool Off
DROP VIEW TEMP3;

/* Query 4 */
Spool result4.lst
SELECT * FROM
(SELECT SS.SID, SPONSOR_NAME, COUNT(*) AS L_NUM
FROM LEAGUES L, SPONSORS SS, SUPPORT SP
WHERE SS.SID = SP.SID AND SP.LID = L.LID
GROUP BY SS.SID, SPONSOR_NAME
ORDER BY SS.SID ASC)
WHERE ROWNUM < 6;
Spool Off

/* Query 5 */
Spool result5.lst
SELECT DISTINCT L.LID, L.LEAGUE_NAME
FROM LEAGUES L, SUPPORT SP
WHERE SP.LID=L.LID
AND (L.SEASON='Autumn' OR L.SEASON='Winter')
AND SP.LID IN (SELECT DISTINCT(SP2.LID) FROM SUPPORT SP2 WHERE SP2.SID IN (SELECT SID FROM SPONSORS S WHERE S.MARKET_VALUE > 50))
AND SP.LID IN (SELECT L2.LID FROM LEAGUES L2 WHERE L2.CHAMPION_TID IN (SELECT DISTINCT(TID) FROM TEAMS WHERE AVERAGE_AGE < 30))
ORDER BY L.LID DESC;
Spool Off

/* Query 6 */
CREATE OR REPLACE VIEW TEMP6 AS
SELECT SS.SID, R.RID, SS.MARKET_VALUE, R.FOOTBALL_RANKING, (SUM(SPONSORSHIP)/(SQRT(SS.MARKET_VALUE) * LOG(2, (SQRT(R.FOOTBALL_RANKING) + 1) ))) AS HOT
FROM REGIONS R, LEAGUES L, SPONSORS SS, SUPPORT SP
WHERE R.RID=L.RID AND L.LID=SP.LID AND SP.SID=SS.SID
GROUP BY SS.SID, R.RID, SS.MARKET_VALUE, R.FOOTBALL_RANKING;
Spool result6.lst
SELECT SID, HOT FROM TEMP6
WHERE HOT=(SELECT MAX(HOT) FROM TEMP6 WHERE FOOTBALL_RANKING < 10 AND MARKET_VALUE > 40)
AND FOOTBALL_RANKING < 10 AND MARKET_VALUE > 40
ORDER BY SID DESC;
Spool Off

/* Query 7 */
Spool result7.lst
SELECT RID, HOT_4, HOT_5, HOT_6, HOT_7, GREATEST(NVL(HOT_4,0),NVL(HOT_5,0),NVL(HOT_6,0),NVL(HOT_7,0)) AS HOT_HIGH FROM(
SELECT R.RID, 
(SELECT HOT FROM TEMP6 T4 WHERE T4.SID=4 AND T4.RID=R.RID) AS HOT_4,
(SELECT HOT FROM TEMP6 T5 WHERE T5.SID=5 AND T5.RID=R.RID) AS HOT_5,
(SELECT HOT FROM TEMP6 T6 WHERE T6.SID=6 AND T6.RID=R.RID) AS HOT_6,
(SELECT HOT FROM TEMP6 T7 WHERE T7.SID=7 AND T7.RID=R.RID) AS HOT_7
FROM REGIONS R)
ORDER BY RID DESC;
Spool Off
DROP VIEW TEMP6;

/* Query 8 */
CREATE OR REPLACE VIEW TEMP8 (TID, NUM) AS
SELECT CHAMPION_TID, COUNT(*) 
FROM LEAGUES 
GROUP BY CHAMPION_TID 
ORDER BY COUNT(*) DESC;
Spool result8.lst
SELECT DISTINCT S.SID, S.SPONSOR_NAME
FROM SPONSORS S, LEAGUES L, SUPPORT SP
WHERE S.SID=SP.SID AND L.LID=SP.LID
AND L.CHAMPION_TID IN (SELECT TID FROM TEMP8 WHERE NUM = (SELECT MAX(NUM) FROM TEMP8))
ORDER BY S.SID ASC;
Spool Off
DROP VIEW TEMP8;
